### ISSUE TITLE
Some suggestion

### ISSUE THREAD

**Issue by symbuzzer** [lehcimcramtrebor/es-theme-basic#3]
Hi sir. Thanks for your superior work. I want to share some of my opinions and suggestions with you.

Is it possible to add options to hide/show flag and stars from game list?

Also can u add support for batocera's show/hide region flag, savestate icon, manual icon, retroachivements icon ... etc options?

Thanks

**Comment by lehcimcramtrebor** [comment]
Hello, this is technically feasible but it would require reworking the location of the other elements so as not to leave empty space.

So I don't think I'll do it, however you can modify it yourself by adding this code just before the last line of the theme.xml file at the root of the theme ) in a view named basic,detailed,grid
	
		<text name="gameRating,gameNorating"
		
			extra="true"
			visible="false".
		
		/>
	
		<image name="md_flag"
		
			visible="false"
		
		/>
		

I chose to simplify the display of indicators in a way that is different from other themes.

You can find the savegames icon, manual icon, retro-achievements etc. in the game lists and grids if you configure emulationstation for that, like in the following screenshots:

![screenshot-2024 10 05-23h18 21](https://github.com/user-attachments/assets/0639feb1-87df-4395-891b-1f64f7b8409f)
![screenshot-2024 10 05-23h18 00](https://github.com/user-attachments/assets/15a19f5e-0b82-461b-be21-f38a04db9804)

For kid games you find a big indicator here:
![EmulationStation 05-10-2024 23-25-25-790](https://github.com/user-attachments/assets/4fe5f00e-fe2b-42ac-ab56-4e45320e127e)

and an small animation here for hidden games:
![EmulationStation 05-10-2024 23-26-40-30](https://github.com/user-attachments/assets/dd7defb6-1878-4d1a-b6b6-32e8eabe2817)

Thank you for your understanding.
